# Generated by Django 6.0.1 on 2026-03-08 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('progress', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswer',
            name='score_breakdown',
            field=models.JSONField(blank=True, help_text='Essay uchun mezonlar bo\'yicha ball: {"content": 8, "vocabulary": 4}', null=True),
        ),
    ]
