# Generated by Django 6.0.1 on 2026-04-01 17:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_level_fields'),
        ('courses', '0004_add_lessoncontent_level'),
        ('progress', '0002_questionanswer_score_breakdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentSessionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='session_logs', to='courses.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_logs', to='accounts.student')),
            ],
            options={
                'db_table': 'student_session_log',
                'ordering': ['-started_at'],
            },
        ),
    ]
