# Generated by Django 6.0.1 on 2026-03-04 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='domain',
            field=models.CharField(blank=True, help_text='Teacher saytining domeni, masalan: https://teacher.example.com', max_length=255, null=True, unique=True),
        ),
    ]
