# Generated by Django 6.0.1 on 2026-03-05 04:07

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_domain_to_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='api_token',
            field=models.CharField(default=accounts.models.generate_api_token, help_text='API ga kirish uchun token. Frontend bu tokenni Authorization headerda yuboradi.', max_length=64, unique=True),
        ),
    ]
