# Generated by Django 6.0.1 on 2026-04-01 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_level_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
