# Generated by Django 6.0.1 on 2026-04-01 17:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_level_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='initial_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.level'),
        ),
        migrations.AddField(
            model_name='student',
            name='placement_done',
            field=models.BooleanField(default=False),
        ),
    ]
