# Generated by Django 6.0.1 on 2026-04-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_lesson_parent_alter_lesson_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('regular', 'Oddiy dars'), ('jn', 'Joriy Nazorat'), ('on', 'Oraliq Nazorat'), ('placement', 'Daraja aniqlash testi')], default='regular', max_length=20),
        ),
    ]
