# Generated by Django 6.0.1 on 2026-04-01 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_level_fields'),
        ('courses', '0003_add_lesson_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoncontent',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_contents', to='accounts.level'),
        ),
    ]
