# Generated by Django 6.0.1 on 2026-06-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_level_fields'),
        ('courses', '0005_moduletype'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modules', to='courses.moduletype'),
        ),
        migrations.AddField(
            model_name='module',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='shared_modules', to='accounts.teacher'),
        ),
    ]
