# Generated by Django 6.0 on 2026-02-01 18:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('config_schema', models.JSONField(blank=True, help_text='Topshiriq turi uchun sozlamalar sxemasi', null=True)),
                ('is_auto_graded', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'assignment_type',
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('total_points', models.IntegerField(default=0, help_text='Avtomatik hisoblanadi')),
                ('time_limit', models.IntegerField(blank=True, help_text='Daqiqalarda', null=True)),
                ('attempts_allowed', models.IntegerField(default=1)),
                ('order_index', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.lesson')),
                ('assignment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='assignments.assignmenttype')),
            ],
            options={
                'db_table': 'assignment',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('question_data', models.JSONField(help_text='Variantlar, juftliklar va h.k.')),
                ('correct_answer', models.JSONField(help_text="To'g'ri javob(lar)")),
                ('points', models.IntegerField(default=1)),
                ('order_index', models.IntegerField(default=0)),
                ('explanation', models.TextField(blank=True, help_text='Javobdan keyin tushuntirish', null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignment')),
            ],
            options={
                'db_table': 'question',
                'ordering': ['order_index'],
            },
        ),
    ]
