# Generated by Django 6.0.1 on 2026-03-08 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmenttype',
            name='is_auto_graded',
        ),
        migrations.AddField(
            model_name='assignmenttype',
            name='grader_type',
            field=models.CharField(choices=[('auto', 'Avtomatik'), ('ai', 'AI'), ('teacher', "O'qituvchi"), ('peer', 'Peer'), ('self', "O'zi"), ('none', 'Baholanmaydi')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.JSONField(blank=True, help_text="To'g'ri javob(lar). AI/teacher grader uchun null bo'lishi mumkin", null=True),
        ),
    ]
