# Generated by Django 6.0.1 on 2026-03-08 06:36

import uuid
from django.db import migrations


ASSIGNMENT_TYPES = [
    {
        'name': 'multiple_choice',
        'description': "Ko'p tanlovli savol",
        'grader_type': 'auto',
        'config_schema': {
            'options_count': {'type': 'integer', 'min': 2, 'max': 6},
            'allow_multiple': {'type': 'boolean'},
        },
    },
    {
        'name': 'true_false',
        'description': "To'g'ri / Noto'g'ri",
        'grader_type': 'auto',
        'config_schema': None,
    },
    {
        'name': 'matching',
        'description': 'Juftliklarga moslashtirish',
        'grader_type': 'auto',
        'config_schema': None,
    },
    {
        'name': 'fill_blank',
        'description': "Bo'sh joyni to'ldirish",
        'grader_type': 'auto',
        'config_schema': None,
    },
    {
        'name': 'ordering',
        'description': "To'g'ri tartibda joylashtirish",
        'grader_type': 'auto',
        'config_schema': None,
    },
    {
        'name': 'short_answer',
        'description': 'Qisqa javob (AI tekshiradi)',
        'grader_type': 'ai',
        'config_schema': {
            'max_words': {'type': 'integer'},
        },
    },
    {
        'name': 'essay',
        'description': "Kengaytirilgan yozma javob, rubrik bo'yicha baholanadi (AI tekshiradi)",
        'grader_type': 'ai',
        'config_schema': {
            'min_words': {'type': 'integer'},
            'max_words': {'type': 'integer'},
            'rubric': {'type': 'object'},
        },
    },
    {
        'name': 'swot',
        'description': 'SWOT tahlil (AI tekshiradi)',
        'grader_type': 'ai',
        'config_schema': {
            'topic': {'type': 'string'},
        },
    },
    {
        'name': 'discussion',
        'description': 'Muhokama / Chat post',
        'grader_type': 'ai',
        'config_schema': {
            'prompt': {'type': 'string'},
        },
    },
    {
        'name': 'file_upload',
        'description': "Fayl yuklash (o'qituvchi tekshiradi)",
        'grader_type': 'teacher',
        'config_schema': {
            'allowed_extensions': {'type': 'array'},
            'max_size_mb': {'type': 'integer'},
        },
    },
    {
        'name': 'goal_setting',
        'description': "SMART maqsadlar va study plan (o'qituvchi tekshiradi)",
        'grader_type': 'teacher',
        'config_schema': None,
    },
    {
        'name': 'peer_assessment',
        'description': 'Boshqa talabaning ishini baholash',
        'grader_type': 'peer',
        'config_schema': {
            'rubric': {'type': 'object'},
        },
    },
    {
        'name': 'self_evaluation',
        'description': "O'z-o'zini baholash formasi",
        'grader_type': 'self',
        'config_schema': None,
    },
    {
        'name': 'video_watch',
        'description': "Video ko'rish vazifasi",
        'grader_type': 'none',
        'config_schema': {
            'video_url': {'type': 'string'},
            'duration_minutes': {'type': 'integer'},
        },
    },
    {
        'name': 'reading',
        'description': "Matn o'qish vazifasi (HTML rich text)",
        'grader_type': 'none',
        'config_schema': {
            'word_count': {'type': 'integer'},
        },
    },
]


def add_assignment_types(apps, schema_editor):
    AssignmentType = apps.get_model('assignments', 'AssignmentType')
    for item in ASSIGNMENT_TYPES:
        AssignmentType.objects.get_or_create(
            name=item['name'],
            defaults={
                'id': uuid.uuid4(),
                'description': item['description'],
                'grader_type': item['grader_type'],
                'config_schema': item['config_schema'],
            },
        )


def remove_assignment_types(apps, schema_editor):
    AssignmentType = apps.get_model('assignments', 'AssignmentType')
    names = [item['name'] for item in ASSIGNMENT_TYPES]
    AssignmentType.objects.filter(name__in=names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_remove_assignmenttype_is_auto_graded_and_more'),
    ]

    operations = [
        migrations.RunPython(add_assignment_types, remove_assignment_types),
    ]
