# Generated by Django 6.0.1 on 2026-03-09 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_api_token'),
        ('assignments', '0003_add_assignment_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmenttype',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text="Bo'sh (null) bo'lsa — barcha o'qituvchilar uchun umumiy", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignment_types', to='accounts.teacher'),
        ),
        migrations.AlterField(
            model_name='assignmenttype',
            name='config_schema',
            field=models.JSONField(blank=True, help_text='Topshiriq turi uchun sozlamalar sxemasi (JSON)', null=True),
        ),
    ]
