# Generated by Django 6.0.1 on 2026-03-09 07:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_add_teacher_to_assignmenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentPart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, null=True)),
                ('order_index', models.IntegerField(default=0)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='assignments.assignment')),
                ('assignment_type', models.ForeignKey(blank=True, help_text="Part uchun alohida topshiriq turi (bo'sh bo'lsa — assignment turidan foydalaniladi)", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='assignments.assignmenttype')),
            ],
            options={
                'db_table': 'assignment_part',
                'ordering': ['order_index'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='part',
            field=models.ForeignKey(blank=True, help_text="Qaysi partga tegishli (bo'sh bo'lsa — partlarsiz assignment)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assignments.assignmentpart'),
        ),
    ]
