# Generated by Django 6.0.1 on 2026-03-09 14:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_teacher_api_token'),
        ('assignments', '0005_add_assignment_part'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('student', 'Student'), ('teacher', "O'qituvchi")], default='student', max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='assignments.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discussion_messages', to='accounts.student')),
            ],
            options={
                'db_table': 'discussion_message',
                'ordering': ['created_at'],
            },
        ),
    ]
