# Generated by Django 6.0.1 on 2026-04-01 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_add_student_level_fields'),
        ('assignments', '0008_assignmentpart_grading_prompt_max_score_speaking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='accounts.level'),
        ),
        migrations.AlterField(
            model_name='assignmentpart',
            name='grading_prompt',
            field=models.TextField(blank=True, help_text="AI ga yuboriladigan baholash mezoni (Speaking uchun)'", null=True),
        ),
        migrations.AlterField(
            model_name='assignmentpart',
            name='max_score',
            field=models.IntegerField(default=5, help_text='Bu part uchun maksimal ball (masalan Part 3 uchun 6)'),
        ),
    ]
