# Generated by Django 6.0.1 on 2026-04-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0009_add_question_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_randomized',
            field=models.BooleanField(default=False, help_text="True bo'lsa savollar tasodifiy tartibda chiqariladi"),
        ),
        migrations.AddField(
            model_name='assignment',
            name='question_count',
            field=models.IntegerField(blank=True, help_text="Tasodifiy tanlanadigan savollar soni (is_randomized=True bo'lsa)", null=True),
        ),
    ]
